import pandas as pd
import numpy as np
import joblib
from sklearn.metrics.pairwise import cosine_similarity
import requests

#Loading the embedded chunks from joblib file created in read_chunks.py
df=joblib.load('new_embeddings.joblib')

# Create embedding matrix once (BIG SPEED IMPROVEMENT)
embedding_matrix = np.vstack(df["embedding"])

def create_embedding(text_list):
    r=requests.post("http://localhost:11434/api/embed",json={
        "model":"bge-m3",
        "input":text_list
    })

    embedding=r.json()['embeddings']
    return embedding

def inference(prompt):
    r=requests.post("http://localhost:11434/api/generate",json={
        "model":"mistral",
        "prompt":prompt,
        "stream":False
    })
    response=r.json()
    return response

#adujusting the seconds to minutes and seconds format for better readability in the answer generated by the LLM
def seconds_to_min_sec(seconds):
    minutes = int(seconds // 60)
    sec = int(seconds % 60)
    return f"{minutes}:{sec:02d}"


incoming_query=input("Ask questions here: ")
question_embedding=create_embedding([incoming_query])[0]

#Calculating the cosine similarity between the incoming question embedding and the chunk embeddings
import sys

# Calculating cosine similarity
similarities = cosine_similarity(
    embedding_matrix,
    [question_embedding]
).flatten()

# Filter relevant chunks
relevant_mask = similarities > 0.35

# If nothing relevant is found
if not relevant_mask.any():
    print("\nThinking...\n")
    print("\nGenerated Answer:\n")
    print("This topic is not covered in the Sigma Web Development course. I can only answer questions related to this course.")
    sys.exit()

# Sorting similarities and selecting top results
top_results = 8
max_indx = similarities.argsort()[::-1][:top_results]

new_df = df.loc[max_indx].copy()

# Convert seconds → minutes:seconds
new_df["start_time"] = new_df["start"].apply(seconds_to_min_sec)
new_df["end_time"] = new_df["end"].apply(seconds_to_min_sec)
#print(new_df[['title','number','text']])

#creating a prompt for the LLM to generate an answer based on the top results
context = new_df[['title','number','start_time','end_time','text']].to_json(orient="records")

prompt = f"""
You are an assistant helping students in the Sigma Web Development course.

Below are subtitle chunks from course videos. Each chunk contains:
- video title
- video number
- start timestamp
- end timestamp
- spoken text

Course Content:
{context}

User Question:
{incoming_query}

Instructions:
- Answer ONLY using the provided video chunks.

- If the answer is not present in the provided chunks, respond ONLY with:
  "This topic is not covered in the Sigma Web Development course. I can only answer questions related to this course."

- Do NOT guess, assume, or fabricate any information.

- Do NOT use words like: "seems", "might", "probably", or "likely".

- Clearly mention:
  1. Video title
  2. Video number
  3. Timestamp in minutes:seconds format

- Guide the student to watch that specific part of the video.

- If the question is unrelated to the course content:
  respond ONLY with this sentence:

  "This topic is not covered in the Sigma Web Development course. I can only answer questions related to this course."

- Do NOT mention any video when the topic is unrelated.

- Do NOT suggest watching any lecture if the topic is unrelated.

- Write the answer in a clear, confident, and natural human way.

- Do NOT create hyperlinks or markdown links.

- Use the timestamp format exactly like: 5:30 (minutes:seconds).
"""
# Debug flag
DEBUG = False

# -----------------------------
# Save prompt for debugging
# -----------------------------
if DEBUG:
    with open("prompt.txt", "w") as f:
        f.write(prompt)

# -----------------------------
# Call LLM
# -----------------------------
print("\nThinking...\n")
api_response = inference(prompt)

# Safely extract response
response = api_response.get("response", "No response returned from the model")

# -----------------------------
# Print answer
# -----------------------------
print("\nGenerated Answer:\n")
print(response)

# -----------------------------
# Save response for debugging
# -----------------------------
if DEBUG:
    with open("response.txt", "w") as f:
        f.write(response)

# -----------------------------
# Optional: inspect retrieved chunks
# -----------------------------
if DEBUG:
    print("\nTop Retrieved Chunks:\n")
    for index, item in new_df.iterrows():
        print(
            f"Index: {index} | "
            f"Title: {item['title']} | "
            f"Video #: {item['number']} | "
            f"Start: {item['start_time']} | "
            f"End: {item['end_time']}"
        )